server:
  port: 8082

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/payment
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


