server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/stock
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
      name: STOCK-SERVICE
