server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url:  jdbc:mysql://${DB_HOST:localhost}:3306/orderz
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

